In [3]:
import numpy as np
a = np.array([10,20,30])
print(a)

[10 20 30]


# Creation, Indexing, and Slicing of Numpy Arrays

In [11]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6]])
print(a)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]]


In [12]:
print(a[1][2])

7


In [13]:
a = np.array([10,20,30,40,50])
print(a[0:3])

[10 20 30]


In [16]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6]])
print(a[0:2,0:2])

[[1 2]
 [5 6]]


In [17]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6]])
print(a[0,1:3])

[2 3]


# inspecting an Array

In [25]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6]])
print(np.shape(a)) #rows, columns
print(np.size(a)) # number of elements 
print(np.ndim(a)) #numbers of dimensions
print(len(a)) #numbers of nested values
print(a.dtype) #datatypes of array
print(a.astype(float)) #convertion of datatypes

(3, 4)
12
2
3
int64
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [9. 8. 7. 6.]]


# Mathematical Operations and Functions on Arrays

In [29]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a + b)
print(np.add(a,b))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [31]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a - b)
print(np.subtract(a,b))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [32]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a * b)
print(np.multiply(a,b))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a / b)
print(np.devided(a,b))

In [34]:
a = np.array([1,2,3,4])
b = np.array([3])
print(np.power(a,b))

[ 1  8 27 64]


In [38]:
a = np.array([1,2,3,4])
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.        ]


# Combining and Splitting Arrays

In [1]:
a = [1,2,3]
b = [2,3,4]
print(a+b)

[1, 2, 3, 2, 3, 4]


In [6]:
#concatenate
import numpy as np
a = np.array([1,2,3])
b = np.array([5,6,7])
print(np.concatenate([a,b]))

[1 2 3 5 6 7]


In [7]:
print(np.concatenate([a,b],axis = 0))

[1 2 3 5 6 7]


In [10]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[5,6,7],[1,2,3]])
print(np.concatenate([a,b],axis = 0))

[[1 2 3]
 [4 5 6]
 [5 6 7]
 [1 2 3]]


In [11]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[5,6,7],[1,2,3]])
print(np.concatenate([a,b],axis = 1))

[[1 2 3 5 6 7]
 [4 5 6 1 2 3]]


In [13]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[5,6,7],[1,2,3]])
print(np.hstack([a,b])) #horizontal concatenation

[[1 2 3 5 6 7]
 [4 5 6 1 2 3]]


In [14]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[5,6,7],[1,2,3]])
print(np.vstack([a,b])) #vertical concatenation

[[1 2 3]
 [4 5 6]
 [5 6 7]
 [1 2 3]]


In [15]:
a = np.array([1,2,3,4,5,6])
b = np.array_split(a,3)
print(b[1])

[3 4]


# Adding and Removing Elements in the Arrays

In [19]:
a = np.array([[1,2,3],[4,5,6]])
#b = np.array([[5,6,7],[1,2,3]])
print(np.append(a,9))
print(np.append(a,[8,10]))

[1 2 3 4 5 6 9]
[ 1  2  3  4  5  6  8 10]


In [20]:
a = np.array([1, 2, 3, 4, 5, 6, 9])
print(np.insert(a,2,11)) #array, index, value

[ 1  2 11  3  4  5  6  9]


In [21]:
a = np.array([[1,2,3],[4,5,6]])
print(np.insert(a,[1,2],[12],axis = 0))

[[ 1  2  3]
 [12 12 12]
 [ 4  5  6]
 [12 12 12]]


In [22]:
print(np.delete(a,1))

[1 3 4 5 6]


# Search, Sort, and Filter Arrays

In [24]:
a = np.array([[5,3,2,12,6],[5,4,3,2,6]])
print(np.sort(a))

[[ 2  3  5  6 12]
 [ 2  3  4  5  6]]


In [27]:
a = np.array([2,3,4,5,6,7,8])
s = np.where(a==6)
ss =  np.searchsorted(a,7)
print(ss)

5


In [29]:
a = np.array([2,3,4,5,6,7,8])
#fl = [True, True, False, False, True, False, False]
fl = a%2==1
new = a[fl]
print(new)

[3 5 7]


# Aggregating Functions in Arrays

In [32]:
a = np.array([2,3,4,5,6,7,8])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

35
2
8
5.0
[ 2  5  9 14 20 27 35]
[    2     6    24   120   720  5040 40320]


In [40]:
a = [100,150,199, 200, 250, 130]
b = [10, 40, 20, 50, 60, 30]

price = np.array(a)
quantity = np.array(b)
print(price, quantity)
print(np.sum(price))
print(np.mean(price))
cum = np.cumprod([price, quantity],axis = 0)
print(cum)
print(cum[1].sum())


[100 150 199 200 250 130] [10 40 20 50 60 30]
1029
171.5
[[  100   150   199   200   250   130]
 [ 1000  6000  3980 10000 15000  3900]]
39880


# Statistical Functions in Arrays

In [47]:
import statistics as stats
baked_food = [200, 300, 150, 130, 200, 280, 170, 188]
a = np.array(baked_food)
print(np.mean(baked_food)) #sum of all the values/number of values
print(np.median(baked_food)) #central value after sorting
print(stats.mode(baked_food))
print(np.std(baked_food))
print(np.var(baked_food))

202.25
194.0
200
55.68157235567257
3100.4375


In [49]:
tobacco_consumption = [30, 50, 10, 30, 50, 40]
deaths = [100, 120, 70, 100, 120, 112]
print(np.corrcoef([tobacco_consumption, deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]
